version: '2'
services:
  nginx_letsencrypt:
    image: registry.cn-hangzhou.aliyuncs.com/c3t3m3/letsencrypt:aliyun
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/common/:/etc/nginx/common/:ro
      - ./etc/fastcgi_params:/etc/nginx/fastcgi_params:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/sites-enabled/:/etc/nginx/sites-enabled:ro
      - ./bin/:/letsencrypt/:ro
      - ./data/webroot/:/usr/share/nginx/html/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:rw
